### ISSUE TITLE
[Backend] Uploading attachment failed

### ISSUE THREAD

**Issue by an920107** [an920107/health-care-website#81]
## Logs

Error message at web console.

```json
{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at tT (https://health-dev.squidspirit.com/_next/static/chunks/245-03e9a9a5379ad0c3.js:6:38320)\n    at XMLHttpRequest.c (https://health-dev.squidspirit.com/_next/static/chunks/245-03e9a9a5379ad0c3.js:6:42968)\n    at et.request (https://health-dev.squidspirit.com/_next/static/chunks/245-03e9a9a5379ad0c3.js:6:50703)\n    at async o.upload (https://health-dev.squidspirit.com/_next/static/chunks/2687-cb1c1743b9ddf65b.js:1:15220)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "multipart/form-data",
            "X-CSRF-Token": "580e27b4-79d7-4abf-9ecb-acbbd3df2292"
        },
        "method": "post",
        "url": "https://health-dev.squidspirit.com/api/attachment",
        "data": {}
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}
```

## Response

The response from the backend server.

```html
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by an920107** [comment]
It seems like to be related with #78.

**Comment by Xunhaoz** [comment]
Bug was fixed.
It happened because of error storing path.
