### ISSUE TITLE
[Frontend] Error occurs when edit insurance 

### ISSUE THREAD

**Issue by an920107** [an920107/health-care-website#84]
## Steps

1. Login and navigate to `/admin/insurance`.
2. Edit a existed insurance record by clicking the pen icon.
3. The error occurs.

## Logs

```log
7023-a29c4925c4a5eac8.js:1  Error: Minified React error #482; visit https://react.dev/errors/482 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nK (fd9d1056-6de46a052172d268.js:1:32328)
    at nJ (fd9d1056-6de46a052172d268.js:1:32814)
    at u (fd9d1056-6de46a052172d268.js:1:38638)
    at fd9d1056-6de46a052172d268.js:1:38869
    at lD (fd9d1056-6de46a052172d268.js:1:57347)
    at l$ (fd9d1056-6de46a052172d268.js:1:59381)
    at iZ (fd9d1056-6de46a052172d268.js:1:117926)
    at ia (fd9d1056-6de46a052172d268.js:1:95165)
    at fd9d1056-6de46a052172d268.js:1:94987
    at il (fd9d1056-6de46a052172d268.js:1:94994)
window.console.error @ 7023-a29c4925c4a5eac8.js:1
l_ @ fd9d1056-6de46a052172d268.js:1
n.callback @ fd9d1056-6de46a052172d268.js:1
nB @ fd9d1056-6de46a052172d268.js:1
nV @ fd9d1056-6de46a052172d268.js:1
aq @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
a9 @ fd9d1056-6de46a052172d268.js:1
aY @ fd9d1056-6de46a052172d268.js:1
(匿名) @ fd9d1056-6de46a052172d268.js:1
is @ fd9d1056-6de46a052172d268.js:1
o1 @ fd9d1056-6de46a052172d268.js:1
oZ @ fd9d1056-6de46a052172d268.js:1
T @ 7023-a29c4925c4a5eac8.js:1
```

**Comment by an920107** [comment]
Addressed in c808a273df6b5bbbff15202e947bca8ff556d1b8.
